---
- name: Install - NFS Provisioner HELM
  uri:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0777'

- name: Install - Git
  yum:
    name:
      - git
    state: present

- name: Install - Get Kubeconfig
  copy:
    src: ./build/kubeconfig
    dest: /tmp/kubeconfig

- name: Install - Install Helm
  command:
    cmd: /tmp/get_helm.sh
  ignore_errors: true

- name: Install - Add Helm repo
  command:
    cmd: /usr/local/bin/helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

- name: Install - Install HELM NFS provisioner
  shell: |
    export KUBECONFIG=/tmp/kubeconfig
    /usr/local/bin/helm install nfs-subdir-external-provisioner \
      nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
      --set nfs.server=100.0.10.130 \
      --set nfs.path=/nfs \
      --set storageClass.onDelete=true
