---
- name: kmaster-00
  box: almalinux/8
  ip: 100.0.10.110
  mem: 4096
  cpu: 2
- name: kworker-00
  box: almalinux/8
  ip: 100.0.10.120
  mem: 4096
  cpu: 2
- name: kworker-01
  box: almalinux/8
  ip: 100.0.10.121
  mem: 4096
  cpu: 2
- name: nfs-server
  box: almalinux/8
  ip: 100.0.10.130
  mem: 2048
  cpu: 1
