---
- hosts:
    - all
  roles:
    - role: init


- hosts:
    - haproxys
  roles:
    - role: haproxy


- hosts:
    - kubernetes
  roles:
    - role: cri
      vars:
        cri: 'docker-ce'
    - role: kubernetes


- hosts:
    - nfs
  roles:
    - role: nfs
    - role: nfs-provisioner
