---
- name: Docker-CE - Remove other Docker versions
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: Docker-CE - Install yum-utils
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils

- name: Docker-CE - Install Docker-CE Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Docker-CE - Install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce-{{ dockerce_version }}
    - docker-ce-cli-{{ dockerce_version }}
    - containerd.io
  notify: Docker-CE-restart

- name: Docker-CE - Create configdir
  file:
    path: /etc/docker
    state: directory

- name: Docker-CE - Set config
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 644
    checksum: 27a3d586165991400d2f4c8e053b5a8b00f45558
  notify: Docker-CE-restart
  when: false

- name: Docker-CE - Add user to 'docker' group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Docker - Force all handlers
  meta: flush_handlers
